[build]
  publish = "public"
  command = "hugo --gc --themesDir themes"

[build.environment]
  HUGO_VERSION = "0.76.5"
  HUGO_THEME = "logbook"
  HUGO_BASEURL = "https://starlord.gr/"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/images/post/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/scss/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/plugins/*/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/plugins/*/*.js"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
