# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
    branches:
      - "master"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  updater:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      WEBHOOK_DISCORD: https://discordapp.com/api/webhooks/bleep/blop
      REPO_PATH: ${{ github.workspace }}/website

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Fetch the repository
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        # the path will be: ${{ github.workspace }}/website
        path: 'website'
        
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        # For the repository the expected format is: {owner}/{repo}.
        repository: 'drpaneas/astrobot'
        # the path will be: ${{ github.workspace }}/astrobotdir
        path: 'astrobotdir'
        
    # Runs a single command using the runners shell
    - run: |
        sudo apt-get install hugo
        cd ${{ github.workspace }}/astrobotdir
        ./astrobot
      
    # Install Go devenv
    # - uses: actions/setup-go@v2
    # - run: go version
    
        
      
